### ISSUE TITLE
Adding Support for Custom Netlify Functions

### ISSUE THREAD

**Issue by LukasOchmann** [netlify/next-on-netlify#36]
As mentioned in the Readme. I need support for custom netlify functions. 
It would at least help to move every thing from "/functions" to the "/out_functions". 
Which i will do myself as an Workaround.

**Comment by FinnWoelm** [comment]
Hey @LukasOchmann! Awesome, we will add that asap. It will probably work like this:

```
next-on-netlify --copy-functions-from=./path/to/functions/dir
```

So in your case, it would be:
```
  "postbuild": "next-on-netlify --copy-functions-from=functions"
```

What do you think of that solution? Would that work for you?

**Comment by ekfuhrmann** [comment]
I too am looking for Custom Netlify Function support to help migrate in GraphQL data. I think the solution proposed here works well, though since Netlify mentions placing the `functions` directory in the root, perhaps it's worth just checking if there is already a `functions` directory and use that, otherwise people can specify the path?

**Comment by cajotafer** [comment]
Sounds like a good option @FinnWoelm , I am doing something similar manually and it works:
```
"postbuild": "next-on-netlify && cp ./functions/* ./out_functions"
```

**Comment by FinnWoelm** [comment]
Hi @lindsaylevine, can you confirm that this issue is resolved with the [new Netlify+Next.js build plugin](https://github.com/netlify/netlify-plugin-nextjs)?

As far as I remember/understand, the build plugin allows you to create custom Netlify functions: Just create the functions as usual in your `functions` folder (or whatever path you set in `netlify.toml`). The build plugin will merge any Next.js-internal functions into your `functions` directory.

If there is a naming-conflict, the build will fail and you will get an error message. So don't worry about accidentally overwriting your custom functions!

If this is indeed the case, we can close this issue 🙂

**Comment by lindsaylevine** [comment]
yes! this is indeed the case! devs can see more info here about the plugin and what's next for next on netlify :) https://github.com/netlify/next-on-netlify#next-on-netlify-roadmap
