### ISSUE TITLE
Static HTML Export

### ISSUE THREAD

**Issue by lucasconstantino** [netlify/next-on-netlify#61]
While this project solves pretty much everything I would need from a product point of view, the fact it heavily relies on Netlify functions - even for routes that could benefit from static exporting - makes the outcome potentially expensive once you reach Netlify's limits for function execution.

I'm wondering if it would be possible easily combine the benefits of both approaches. The idea would be to reuse `next export` results, and then adapt `next-on-netlify` redirects so those direct paths to statically exported HTML can be used as is, with no function related to it - while still fall-backing to the serverless route when reaching a non-built route.

This could potentially reduce build time - my project went from 3m to 7m after installing this package - and highly decrease usage costs overall.

**Comment by lucasconstantino** [comment]
By the way: I made a very similar project targeting specifically API Routes usage on static exported sites running on Netlify: [`next-export-api`](https://github.com/lucasconstantino/next-export-api)

**Comment by FinnWoelm** [comment]
Hi @lucasconstantino, thank you for filing this issue and apologies for the late reply!

Can you share more about where you see potential benefits for more static exporting? next-on-netlify statically exports as much as possible: static pages (with or without dynamic routing) and pages with getStaticProps (with or without dynamic routing). Pages with `getInitialProps` and `getServerSideProps` as well as API routes are set up as Netlify Functions, so that they can be server-side-rendered. This gives users full control: If they want a pre-rendered, static page, they can use `getStaticProps`. Otherwise, if they want dynamic, SSRed pages, they can use `getServerSideProps`.

Thanks for sharing the link to `next-export-api` 😊 Great work 🙂

**Comment by lindsaylevine** [comment]
hey @lucasconstantino!! i think we can close this discussion as it's been about a month since finn's reply, and i generally agree with finn that we're limiting functions usage as much as we possibly can in next-on-netlify. feel free to re-open if you can make a case for next export that accommodates all the framework's features and complexity!!! 🙏 <3
