### ISSUE TITLE
Support for Next/Image

### ISSUE THREAD

**Issue by lokmanm** [netlify/next-on-netlify#70]
Hello everyone, as you might already know Next now has a new [Image Component](https://nextjs.org/docs/api-reference/next/image) and I was thinking if its possible to support it on Netlify ?

At our company we are very tight with the whole Netlify ecosystem, we use Netlify CMS and we use Netlify for publishing almost everything that we have & we cant afford to switch to Vercel just for this component.

The new Image component is very good but sadly I found out that they only support that on Vercel hosted sites, We are not very familiar with `next-on-netlify` thus we can't do a PR, but we are willing to help out during the PR with testing, docs, or whatever is needed.

Thank you

**Comment by etrepum** [comment]
The absolute simplest thing you could do today would be to use imgix, akamai, or cloudinary as an image optimizing CDN. Yeah, it's not provided by Netlify, but you also don't have to change how anything is deployed.

The Netlify options don't seem very low friction. There is [Netlify Large Media Transformations](https://docs.netlify.com/large-media/transform-images/) but it requires that you set up Git LFS for those assets and it would also require a patch to next.js to support that URL scheme.

It would be possible to deploy the new next.js image optimizer (`/_next/image`) as a Netlify Function, but the performance would not be very good because it uses the local disk to persist the cache so every request would be a cache miss and have to do the optimization each time.
