### ISSUE TITLE
netlify.toml redirects aren't obeyed

### ISSUE THREAD

**Issue by ChrisBAshton** [netlify/next-on-netlify#80]
Situation: I was trying to allow requests to `/random` to be proxied to `/api/random`.

I edited my `netlify.toml` to add this:

```toml
[[redirects]]
  from = "/random" 
  status = 200 # turns the redirect into a proxy
  to = "/api/random"
```

But ended up getting this output under `out_publish/_redirects` (i.e. the custom proxy wasn't registered):

```
# Next-on-Netlify Redirects
/  /.netlify/functions/next_index  200
/api/random  /.netlify/functions/next_api_random  200
/*  /:splat  200
```

I tried creating a `_redirects` file instead:

```
/random /api/random 200
```

This was being picked up in the output 🎉 

```
/random /api/random 200!

# Next-on-Netlify Redirects
/  /.netlify/functions/next_index  200
/api/random  /.netlify/functions/next_api_random  200
/*  /:splat  200
```

However, requests to `/random` continued to 404. I guessed this was because [Netlify only allow one hop](https://docs.netlify.com/routing/redirects/rewrites-proxies/#limitations). So I changed the contents or `_redirects` to:

`/random /.netlify/functions/next_api_random 200!`

...and now it's doing what I want 😁 

I don't think there's much we can do about the one-hop limit, but [next-on-netlify claims to look at the netlify.toml for redirects](https://github.com/netlify/next-on-netlify#custom-netlify-redirects), and that doesn't appear to be working 🤔 is this a bug?

**Comment by lindsaylevine** [comment]
ahhhh @ChrisBAshton thanks so much for opening this!!! i don't know when that snuck into the README but no, you are 100% right, we do not support toml-based redirects. it's a known issue on an internal list i keep. so sorry you spent time confused on that. for now, i'll update the README, and i'll leave this issue open so i can update you when this finally gets addressed.

**Comment by ChrisBAshton** [comment]
Thanks for the quick response, @lindsaylevine! 👍

**Comment by FinnWoelm** [comment]
Hi both!

If it's okay, I'm going to close this issue, since the misleading comment in the README has been removed.

By the way, redirects from `netlify.toml` do actually work. But they are processed **after** redirects created by `next-on-netlify`. So, in your case, where you have a catch-all redirect generated by `next-on-netlify`, it would not reach the custom redirect you created in `netlify.toml`. In that case, you do indeed need to use the `_redirects` file here. This is all in accordance with the ["Rule processing order" provided by Netlify](https://docs.netlify.com/routing/redirects/#rule-processing-order). But it was certainly misleading, so it's probably good to have it removed from the README.

We do want to add support for Next.js redirects and rewrites (#24) at some point, which would make all of this a lot easier for end users 😊
