### ISSUE TITLE
Discussion: inlining next-aws-lambda vs fixing upstream and other alternatives

### ISSUE THREAD

**Issue by lindsaylevine** [netlify/next-on-netlify#95]
stakeholders: @FinnWoelm @ehmicky 

This issue is to publicly discuss an internal discussion around inlining next-aws-lambda.

Original issues with depending on next-aws-lambda:
1. plugin dependency issue (https://github.com/netlify/netlify-plugin-nextjs/issues/10) (this is being addressed internally)
2. miscellaneous user-reported issues

To move forward and relieve some tension with these open issues, we've temporarily inlined next-aws-lambda with Finn's awesome [PR](https://github.com/netlify/next-on-netlify/pull/92). However, @ehmicky brought up concerns around future maintenance issues with inlining. 

Options:
1. Inline the package (most fine-grained control but needing to repeatedly update a semi-active project)
2. Use patch-package
3. Fork the project (monorepo though)
4. Open PRs upstream (this could benefit both the greater Next.js community and other Netlify plugins)

While we all agree inlining is a great first step and improvement from what we had for the original issues, let's try to align on the best path forward.

**Comment by ehmicky** [comment]
Thanks for opening this @lindsaylevine!
For information, this is the [link to `patch-package`](https://github.com/ds300/patch-package).

I think opening PRs upstream to solve those problems in `next-aws-lambda` would be better since it could benefit the greater Next.js community as you mention. Also, the current inlining would require any update of the two inlined files in `next-aws-lambda` to be ported to this repository manually.

**Comment by FinnWoelm** [comment]
Hmmm! Good points! I see the strong benefits of opening PRs upstream!

**How about the following proposal:** We continue with inlined next-aws-lambda for now, which is already 95% done and allows us to fix the two remaining compatibility-layer-related issues #82 and #20 asap. As we go on, @lindsaylevine and I will periodically check for updates made to next-aws-lambda ([source code](https://github.com/serverless-nextjs/serverless-next.js/tree/master/packages/compat-layers/apigw-lambda-compat) and [changelog](https://github.com/serverless-nextjs/serverless-next.js/blob/master/packages/compat-layers/apigw-lambda-compat/CHANGELOG.md)). If, say in a couple months time, we realize that this inlining approach is creating a headache because we have to manually copy over a bunch of patches all the time, let's reevaluate then and perhaps invite Daniel Conde (the creator and maintainer of the package) for a Zoom chat to discuss how we can best integrate any Netlify-specific needs. How does that sound?

PS: If we need to justify the inlining for now, we could use the following three arguments:

1. According to the [changelog](https://github.com/serverless-nextjs/serverless-next.js/blob/master/packages/compat-layers/apigw-lambda-compat/CHANGELOG.md) and [git blame](https://github.com/serverless-nextjs/serverless-next.js/blame/master/packages/compat-layers/apigw-lambda-compat/lib/compatLayer.js), `next-aws-lambda` has received only four or five minor patches over the last 15 months (most version changes are just version bumps to keep it aligned with the other packages in that monorepo)
1. The large majority of the userbase of `next-aws-lambda` are our own users: [`next-aws-lambda`](https://www.npmjs.com/package/next-aws-lambda) has 8.5k weekly downloads, [6.5k of which come from NoN users](https://www.npmjs.com/package/next-on-netlify)
![image](https://user-images.githubusercontent.com/7606194/99618719-d858fb00-2a5c-11eb-8435-1087dda53a4b.png)
![image](https://user-images.githubusercontent.com/7606194/99618731-e149cc80-2a5c-11eb-9dee-695629ebb070.png)
1. The maintainers of `next-aws-lambda` are currently focused on using AWS Lambda@edge infrastructure rather than AWS lambda (see https://github.com/serverless-nextjs/serverless-next.js/issues/296). `next-aws-lambda` is only used in their *deprecated* next-serverless-plugin. Although, this thread sounds like that may change in the future: https://github.com/serverless-nextjs/serverless-next.js/issues/777 — a good reason to keep a close eye on developments and reevaluate our decision once we have more information!

**Comment by FinnWoelm** [comment]
PPS: I am **personally** very interested to learn more about the patch-package approach (even though I think for the sake of next-on-netlify, we should continue with inlining `next-aws-lambda` for now and then reevaluate in a couple months based on how our experience goes).

I've used and suggested patch-package to users before (see #20), but the workflow was never really smooth for the end user as they had to manually copy patches (`copy -r ./node_modules/next-on-netlify/patches ./patches`). `patch-package` is not built to support libraries/modules supplying their own patches to avoid situations where one of your dependencies gets patched by one module and then is incompatible with another module, as explained [here](https://github.com/ds300/patch-package/issues/198) and [here](https://github.com/ds300/patch-package/issues/26). If you know a way around that, I would be very keen to learn 😊

**Comment by ehmicky** [comment]
This is a very pragmatic approach @FinnWoelm, love it! :heart:

**Comment by FinnWoelm** [comment]
Ok 😊 PS: Your work and improvements to next-on-netlify and the Next.js plugin are AMAZING 🎉 🙌 🙌

**Comment by lindsaylevine** [comment]
hey all, closing this since the discussion is over :). per the resolution we reached, if/when we run into issues manually updating what's inlined, we can re-address then!
